apps/project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path("create/",
         views.ProjectCreateView.as_view(),
         name="create_project_url"
         ),
    path("list/",
         views.ProjectListView.as_view(),
         name="project_list_url"
         ),
    path("detail/<int:pk>/",
         views.ProjectDetailView.as_view(),
         name="project_detail_url"
         ),
    path("update/<int:pk>/",
         views.ProjectUpdateView.as_view(),
         name="project_update_url"
         ),
    path("delete/<int:pk>/",
         views.ProjectDeleteView.as_view(),
         name="project_delete_url"
         ),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.HomeTemplateView.as_view(), name="home_url"),
    path('', include('users.urls', namespace='users')),

    path('project/', include('project.urls', namespace='project')),
    path('administrator/', include('admindashboard.urls', namespace='administrator')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

apps/project/models.py
from django.db import models
from django.utils.text import slugify
from uuid import uuid4
from config.models import CreationModificationDateBase


class Project(CreationModificationDateBase):
    id = models.UUIDField(primary_key=True,
                          default=uuid4,
                          editable=False
                          )
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,
                            unique=True
                            )
    description = models.TextField()
    end_date = models.DateField(null=True,
                                blank=True
                                )
    created_by = models.ForeignKey("users.CustomUser",
                                   on_delete=models.CASCADE,
                                   related_name="projects_created"
                                   )
    STATUS_CHOICES = [
        ("in_progress", "In Progress"),
        ("completed", "Completed"),
        ("on_hold", "On Hold")
    ]
    status = models.CharField(max_length=20,
                              choices=STATUS_CHOICES,
                              default="in_progress"
                              )
    is_active = models.BooleanField(default=True)
    teams = models.ManyToManyField('teams.Team',
                                   related_name='projects'
                                   )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_tasks(self):
        return self.tasks.all()

apps/project/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings

from .models import Project


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    template_name = 'project_form.html'
    fields = ('name', 'description', 'end_date',
              'assigned_to', 'status', 'is_active')
    success_url = reverse_lazy('project:project_list_url')
    login_url = settings.LOGIN_URL

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    template_name = 'project_list.html'
    context_object_name = 'projects'
    login_url = settings.LOGIN_URL


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project
    template_name = 'project_detail.html'
    context_object_name = 'project'
    login_url = settings.LOGIN_URL


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    template_name = 'project_form.html'
    fields = ('name', 'description')
    success_url = reverse_lazy('project:project_list_url')
    login_url = settings.LOGIN_URL


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    template_name = 'project_confirm_delete.html'
    success_url = reverse_lazy('project:project_list_url')
    login_url = settings.LOGIN_URL

apps/project/templates/project_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Delete Projects {{project}}
{% endblock title %}

{% block leftbar %}
    <div class="col-sm-3">

    </div>
{% endblock leftbar %}
{% block content %}
    <div class="col-sm-9">
        <form action="" method="post">
            {% csrf_token %}
            <p class="lead">You are about to delete Project: '{{project}}'. Do you want to preceed?</p>
            <button type="submit" class="btn btn-sm btn-outline-danger">Yes</button>
            <a href="{% url 'project:project_detail_url' project.id %}" type="submit" class="btn btn-sm btn-outline-primary">No</a>
        </form>
    </div>
{% endblock content %}

apps/project/templates/project_detail.html
{% extends 'base.html' %}

{% block title %}
Projects {{project}}
{% endblock title %}

{% block leftbar %}
    <div class="col-sm-3">

    </div>
{% endblock leftbar %}
{% block content %}
    <div class="col-sm-9">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{project.name}}</li>
            <li class="list-group-item">{{project.description}}</li>
            <li class="list-group-item">
                <a href="{% url 'project:project_update_url' project.id %}" type="button" class="btn btn-sm btn-outline-primary">Edit</a>
                <a href="{% url 'project:project_delete_url' project.id %}" type="button" class="btn btn-sm btn-outline-danger">Delete</a>
            </li>
        </ul>
    </div>
{% endblock content %}

apps/project/templates/project_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block title %}
Projects {% if 'create' in request.path %}Create {% else %}Update{% endif %} Form
{% endblock title %}

{% block leftbar %}
    <div class="col-sm-3">

    </div>
{% endblock leftbar %}
{% block content %}
    <div class="col-sm-9">
        <form action="" method="post">
            <legend class="border-bottom">{% if 'create' in request.path %}Create {% else %}Update{% endif %} Project</legend>
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-sm btn-ouline-primary mt-2">{% if 'create' in request.path %}Create {% else %}Update{% endif %} Project</button>
        </form>
    </div>
{% endblock content %}

apps/project/templates/project_list.html
{% extends 'base.html' %}

{% block title %}
Projects
{% endblock title %}

{% block leftbar %}
    <div class="col-sm-3">

    </div>
{% endblock leftbar %}
{% block content %}
    <div class="col-sm-9">
        {% for project  in projects %}
            <a href="{% url 'project:project_detail_url' project.id %}">{{project}}</a>
        {% endfor %}
    </div>
{% endblock content %}