apps/project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path("create/",
         views.ProjectCreateView.as_view(),
         name="create_project_url"
         ),
    path("list/",
         views.ProjectListView.as_view(),
         name="project_list_url"
         ),
    path("detail/<int:pk>/",
         views.ProjectDetailView.as_view(),
         name="project_detail_url"
         ),
    path("update/<int:pk>/",
         views.ProjectUpdateView.as_view(),
         name="project_update_url"
         ),
    path("delete/<int:pk>/",
         views.ProjectDeleteView.as_view(),
         name="project_delete_url"
         ),
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    ########### User Account #############
    path('register/',
         views.register,
         name='register'
         ),

    path('profile/',
         views.profile,
         name='profile'
         ),

    path('',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),

    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'
         ),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'
         ),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'
         ),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.HomeTemplateView.as_view(), name="home_url"),
    path('', include('users.urls', namespace='users')),

    path('project/', include('project.urls', namespace='project')),
    path('administrator/', include('admindashboard.urls', namespace='administrator')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

templates/partials/_header.html
{% comment %} comment the whole header page if one or more apps are being deleted. {% endcomment %}

templates/partials/_leftbar.html
  <ul class="list-group mt-2">
    <li class="list-group-item active">
    Leftbar
    </li>
    <li class="list-group-item">
    <a href="{% url 'project:project_list_url' %}">Projects</a>
    </li>
    
  </ul>

templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top fixed-top ">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home_url' %}">Project Management App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="#">{{ request.user|capfirst }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'users:logout' %}">logout</a>
          </li>
        {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>

templates/partials/_paginator.html
    {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}

templates/partials/_scripts.html
{% load static %}
<script src="{% static 'js/vendor/jquerry.js' %}"></script>
<script src="{% static 'js/vendor/popper.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/lightbox_bs5.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/site_js.js' %}"></script>