apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    ########### User Account #############
    path('register/',
         views.register,
         name='register'
         ),

    path('profile/',
         views.profile,
         name='profile'
         ),

    path('',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),

    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'
         ),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'
         ),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'
         ),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.HomeTemplateView.as_view(), name="home_url"),
    path('', include('users.urls', namespace='users')),

    path('project/', include('project.urls', namespace='project')),
    path('administrator/', include('admindashboard.urls', namespace='administrator')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

apps/users/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from PIL import Image


class Organization(models.TextChoices):
    A = 'A', _("A")
    B = 'B', _("B")


class CustomUser(AbstractUser):
    orig_name = models.CharField(
        choices=Organization.choices, max_length=2)
    age = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=21, null=True, blank=True)


class Profile(models.Model):
    user = models.OneToOneField("users.CustomUser", on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from .models import CustomUser as User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email',
                  'orig_name', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import CustomUser as User


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Your account with {username} has been created! You are now able to log in')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

apps/users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Log In
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}

{% block content %}
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <form method="POST" action=''>
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Log In</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-sm btn-outline-info mt-2" type="submit">Login</button>
                        <small class="text-muted ml-3">
                            <a href="{% url 'users:password_reset' %}">Forgot Password?</a>
                        </small>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Need An Account? <a class="ml-2" href="{% url 'users:register' %}">Sign Up Now</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/users/templates/users/logout.html
{% extends "base.html" %}

{% block title %}
Log Out
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}

{% block content %}
<div class="col-sm-8">
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:login' %}" class="btn btn-outline-info" role="button">Log In Again</a>
        </small>
    </div>
</div>
{% endblock content %}

apps/users/templates/users/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Reset Password
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}
{% block content %}
<div class="col-sm-8">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

apps/users/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block title %}
Password Reset Complete
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}
{% block content %}
<div class="col-sm-8">
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'users:login' %}" class="btn btn-primary" role=button> Sign In Here</a>
</div>
{% endblock content %}

apps/users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Password Reset Confirm
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}
{% block content %}
<div class="col-sm-8">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

apps/users/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}
Password Reset Done
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}
% block content %
<div class="col-sm-8">
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
</div>
{% endblock content %}

apps/users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %}
  {{ request.user.username|capfirst }}'s Profile
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}

{% block content %}
    <div class="col-sm-7">
      <div class="content-section">
        <div class="media">
          <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
          <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
          </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
      </div>
    </div>
{% endblock content %}

apps/users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Register
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}

{% block content %}
<div class="col-sm-7">
    <div class="content">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Register</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-sm btn-outline-info mt-2" type="submit">Sign Up</button>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Already Have An Account? <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/users/templates/users/registration_under_approval.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block on_page_css %}
{% endblock on_page_css %}

{% block title %}
Registration Under Approval
{% endblock title %}

{% block leftbar %}
<div class='col-sm-3'>
</div>
{% endblock leftbar %}

{% block content %}
<div class='col-sm-9 mt-2' id='main-div'>
    <div class="alert alert-primary" role="alert">
        Dear User {{ self.request.user }}! Your registration is under approval.
    </div>
</div>
{% endblock content %}

{% block model %}
{% endblock model %}

{% block on_page_script %}
{% endblock on_page_script %}